# Generated by Django 5.2.4 on 2025-08-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'นักเรียน', 'verbose_name_plural': 'นักเรียน'},
        ),
        migrations.RenameField(
            model_name='students',
            old_name='sitd',
            new_name='student_id',
        ),
    ]
